name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  setup-go:
    name: Set up Go 1.23
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup-go
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run tests
        run: go test -v ./...

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build application
        run: go build -o web-go-app
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    needs: setup-go
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3

      - name: Run golangci-lint
        run: golangci-lint run ./...

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/web-go-app:${{ github.run_id }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/web-go-app:${{ github.run_id }}

  update-helm-chart:
    name: Update Helm Chart with New Image Tag
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update tag in values.yml
        run: |
          sed -i "s/tag:.*/tag: ${{ github.run_id }}/" helm/web-go-app-chart/values.yaml

      - name: Commit changes
        run: |
          git config --local user.email "espr1997@gmail.com"
          git config --local user.name "shiva270597"
          git add helm/web-go-app-chart/values.yaml
          git commit -m "Update image tag in values.yaml to ${{ github.run_id }}"
          git push
